"""The rules a periodic register must not be scored against

Docs: https://AnswerDotAI.github.io/slopometer/house.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_house.ipynb.

# %% auto #0
__all__ = ['HOUSE_DROP', 'HOUSE_HEDGES', 'HOUSE_BANNED', 'apply_profile']

# %% ../nbs/09_house.ipynb #house03
import os

from fastcore.utils import *

from . import lexicon
from .core import rules, KILL, SMELL
from .lexicon import lex_rule, hedges

# %% ../nbs/09_house.ipynb #house05
HOUSE_DROP = {
    'sent_len':    'the periodic sentence is the form, not a defect',
    'clauses':     'subordination is how a period is built',
    'semi_splice': "the semicolon join is the register's chief instrument",
    'splice':      'so is the dash aside',
    'passive':     '"What is done from necessity..." is Johnson\'s sentence, not a lapse',
    'variation':   'two words for one thing is a deliberate device here, not an accident',
    'conseq':      '", so" as consequence glue reads as speech, which is wanted',
}

# %% ../nbs/09_house.ipynb #house07
HOUSE_HEDGES = {k: v for k, v in hedges.items() if k in {
    'potentially', 'in some cases', 'should generally', 'may or may not',
    'one might argue', 'it could be argued', 'arguably', 'more or less'}}

# %% ../nbs/09_house.ipynb #house07b
HOUSE_BANNED = {
    'quietly': None,  # names a concealment without naming what was concealed
}

# %% ../nbs/09_house.ipynb #house09
_stash = {}


def apply_profile(
    name: str = None,  # Profile to apply; `$SLOPOMETER_PROFILE` when None, and 'house' when that is unset
) -> list:
    "Amend the rule registry in place for `name`, returning the rules this call removed"
    from slopometer import syntax, para  # every rule must be registered before any is pruned
    if (name or os.environ.get('SLOPOMETER_PROFILE', 'house')) != 'house':
        rules.update(_stash)
        _stash.clear()
        lexicon.find_hedges = lex_rule('hedges', tell=7, weight=SMELL, lex=hedges)
        rules.pop('house_banned', None)
        return []
    out = []
    for n in HOUSE_DROP:
        if (r := rules.pop(n, None)) is not None:
            _stash[n] = r
            out.append(n)
    lexicon.find_hedges = lex_rule('hedges', tell=7, weight=SMELL, lex=HOUSE_HEDGES)
    lex_rule('house_banned', tell=None, weight=KILL, lex=HOUSE_BANNED)
    return out
